#http
version: '3.8'
services:
  znc:
    image: znc:latest@sha256:e0501a44a45a625c4255f1470cbd57436c03a9592a3f6668278a0fdfe43bf8c5
    ports:
      - "4722:4722"
    volumes:
      - znc-data:/znc-data
    restart: "no"
volumes:
  znc-data:
